# Generated by Django 3.2.4 on 2021-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2048)),
                ('status', models.IntegerField()),
                ('response_time', models.CharField(max_length=5)),
                ('regexp', models.CharField(blank=True, max_length=1024, null=True)),
                ('regexp_match', models.BooleanField(blank=True, null=True)),
                ('match_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
