# Generated by Django 3.2.4 on 2021-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2048)),
                ('status', models.IntegerField()),
                ('response_time', models.DurationField()),
            ],
        ),
    ]
