# Generated by Django 3.2.4 on 2021-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='response_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
