# Generated by Django 3.2.4 on 2021-06-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_alter_url_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='regexp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
