# Generated by Django 3.2.4 on 2021-06-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_url_regexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='regexp',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
