# Generated by Django 3.2.4 on 2021-06-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0004_alter_url_regexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='regexp_match',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
