# Generated by Django 3.2.4 on 2021-06-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0005_url_regexp_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='match_details',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
