# Generated by Django 3.2.4 on 2021-06-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0006_url_match_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='regexp_match',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
