# Generated by Django 3.2.4 on 2021-07-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0007_alter_url_regexp_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='regexp',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
