# Generated by Django 3.2.4 on 2021-07-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0008_alter_url_regexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='regexp',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='regexp_match',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
