# Generated by Django 3.2.4 on 2021-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0010_alter_url_regexp_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='match_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
