# Generated by Django 3.2.4 on 2021-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0011_alter_url_match_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='match_details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
