# Generated by Django 3.2.4 on 2021-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0013_alter_url_match_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='response_time',
            field=models.CharField(max_length=5),
        ),
    ]
